export const hotelData = {
  rateDates: [
    {
      RateDate: "2023-07-01T00:00:00",
    },
    {
      RateDate: "2023-07-02T00:00:00",
    },
    {
      RateDate: "2023-07-03T00:00:00",
    },
    {
      RateDate: "2023-07-04T00:00:00",
    },
    {
      RateDate: "2023-07-05T00:00:00",
    },
  ],
  //   hotelNames: [
  //     {
  //       HotelName: "Candlewood Suites University / College Station TX",
  //     },
  //     {
  //       HotelName: "Hilton Garden Inn",
  //     },
  //     {
  //       HotelName: "Holiday Inn Express Bryan",
  //     },
  //     {
  //       HotelName: "La Quinta Inn & Suites North",
  //     },
  //   ],
  compSetHotelsRates: [
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Studio Suite",
      BarRate: 185,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil Tub)",
      BarRate: 155,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil)",
      BarRate: 155,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Kitchen",
      BarRate: 155,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible (Comm, Mobil Tub)",
      BarRate: 185,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible, Kitchen (Comm)",
      BarRate: 185,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Kitchen",
      BarRate: 185,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Suite, 1 Bedroom, Accessible (1 King, Comm, Mobil Tub)",
      BarRate: 214,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Suite, 1 Bedroom, Kitchen (1 King, Living, Dining)",
      BarRate: 214,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Studio Suite",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil Tub)",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil)",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Kitchen",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible (Comm, Mobil Tub)",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible, Kitchen (Comm)",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Kitchen",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Suite, 1 Bedroom, Accessible (1 King, Comm, Mobil Tub)",
      BarRate: 207,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Suite, 1 Bedroom, Kitchen (1 King, Living, Dining)",
      BarRate: 207,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Studio Suite",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil Tub)",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil)",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Kitchen",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible (Comm, Mobil Tub)",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible, Kitchen (Comm)",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Kitchen",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Suite, 1 Bedroom, Accessible (1 King, Comm, Mobil Tub)",
      BarRate: 207,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Suite, 1 Bedroom, Kitchen (1 King, Living, Dining)",
      BarRate: 207,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Studio Suite",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil Tub)",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil)",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Kitchen",
      BarRate: 147,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible (Comm, Mobil Tub)",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible, Kitchen (Comm)",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Kitchen",
      BarRate: 162,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Suite, 1 Bedroom, Accessible (1 King, Comm, Mobil Tub)",
      BarRate: 207,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Suite, 1 Bedroom, Kitchen (1 King, Living, Dining)",
      BarRate: 207,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Studio Suite",
      BarRate: 199,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil Tub)",
      BarRate: 185,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Accessible (Comm, Mobil)",
      BarRate: 185,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Studio Suite, 1 Queen Bed, Kitchen",
      BarRate: 185,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible (Comm, Mobil Tub)",
      BarRate: 199,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Accessible, Kitchen (Comm)",
      BarRate: 199,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Studio Suite, 2 Queen Beds, Kitchen",
      BarRate: 199,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Suite, 1 Bedroom, Accessible (1 King, Comm, Mobil Tub)",
      BarRate: 244,
    },
    {
      HotelName: "Candlewood Suites University / College Station TX",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Suite, 1 Bedroom, Kitchen (1 King, Living, Dining)",
      BarRate: 244,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Room, 1 King Bed",
      BarRate: 183,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Room, 1 King Bed (Drinks-Snacks)",
      BarRate: 226,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-01T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 183,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-01T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 183,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Room, 2 Queen Beds",
      BarRate: 197,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-01T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 197,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-01T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 197,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Room, 2 Queen Beds, Non Smoking (Drinks-Snacks)",
      BarRate: 226,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Room, Accessible",
      BarRate: 197,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Room, 1 King Bed",
      BarRate: 137,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Room, 1 King Bed (Drinks-Snacks)",
      BarRate: 163,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-02T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 137,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-02T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 137,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Room, 2 Queen Beds",
      BarRate: 137,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-02T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 137,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-02T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 137,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Room, 2 Queen Beds, Non Smoking (Drinks-Snacks)",
      BarRate: 163,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Room, Accessible",
      BarRate: 137,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Room, 1 King Bed",
      BarRate: 137,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Room, 1 King Bed (Drinks-Snacks)",
      BarRate: 163,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-03T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 137,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-03T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 137,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Room, 2 Queen Beds",
      BarRate: 137,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-03T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 137,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-03T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 137,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Room, 2 Queen Beds, Non Smoking (Drinks-Snacks)",
      BarRate: 163,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-03T00:00:00",
      RoomType: "Room, Accessible",
      BarRate: 137,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Room, 1 King Bed",
      BarRate: 138,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Room, 1 King Bed (Drinks-Snacks)",
      BarRate: 164,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-04T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 138,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-04T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 138,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Room, 2 Queen Beds",
      BarRate: 138,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-04T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 138,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-04T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 138,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Room, 2 Queen Beds, Non Smoking (Drinks-Snacks)",
      BarRate: 164,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-04T00:00:00",
      RoomType: "Room, Accessible",
      BarRate: 138,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Room, 1 King Bed",
      BarRate: 138,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Room, 1 King Bed (Drinks-Snacks)",
      BarRate: 163,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-05T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 138,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-05T00:00:00",
    //   RoomType: "Room, 1 King Bed, Accessible",
    //   BarRate: 138,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Room, 2 Queen Beds",
      BarRate: 138,
    },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-05T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 138,
    // },
    // {
    //   HotelName: "Hilton Garden Inn",
    //   RateDate: "2023-07-05T00:00:00",
    //   RoomType: "Room, 2 Queen Beds, Accessible",
    //   BarRate: 138,
    // },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Room, 2 Queen Beds, Non Smoking (Drinks-Snacks)",
      BarRate: 163,
    },
    {
      HotelName: "Hilton Garden Inn",
      RateDate: "2023-07-05T00:00:00",
      RoomType: "Room, Accessible",
      BarRate: 138,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Standard Room",
      BarRate: 241,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Standard Room, 1 King Bed (Walk In Shower)",
      BarRate: 201,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Standard Room, 1 King Bed, Accessible (Comm)",
      BarRate: 201,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType:
        "Standard Room, 1 King Bed, Accessible (Comm, Mobil, Roll Shwr)",
      BarRate: 201,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType:
        "Standard Room, 1 King Bed, Accessible (Comm, Mobil, Tran Shwr)",
      BarRate: 201,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Standard Room, 2 Queen Beds",
      BarRate: 229,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Standard Room, 2 Queen Beds, Accessible (Comm)",
      BarRate: 229,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Standard Room, 2 Queen Beds, Accessible (Comm, Mobil, Tub)",
      BarRate: 0,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Suite, 1 Bedroom (Walk In Shower)",
      BarRate: 221,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Suite, 1 Bedroom, Accessible (Comm, Mobil, Tub)",
      BarRate: 0,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Suite, 1 Bedroom, Accessible (Comm, Roll Shwr)",
      BarRate: 221,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Suite, 2 Bedrooms, Accessible (Comm, Mobil, Tub)",
      BarRate: 0,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-01T00:00:00",
      RoomType: "Suite, Multiple Beds",
      BarRate: 241,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Standard Room",
      BarRate: 172,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Standard Room, 1 King Bed (Walk In Shower)",
      BarRate: 172,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Standard Room, 1 King Bed, Accessible (Comm)",
      BarRate: 172,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-02T00:00:00",
      RoomType:
        "Standard Room, 1 King Bed, Accessible (Comm, Mobil, Roll Shwr)",
      BarRate: 172,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-02T00:00:00",
      RoomType:
        "Standard Room, 1 King Bed, Accessible (Comm, Mobil, Tran Shwr)",
      BarRate: 172,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Standard Room, 2 Queen Beds",
      BarRate: 172,
    },
    {
      HotelName: "Holiday Inn Express Bryan",
      RateDate: "2023-07-02T00:00:00",
      RoomType: "Standard Room, 2 Queen Beds, Accessible (Comm)",
      BarRate: 172,
    },
  ],
};
